version: '3.8'

services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      # - POSTGRES_DB=geodb
    ports:
      - 5435:5432
    volumes:
      - ./postgis:/docker-entrypoint-initdb.d

  python:
    build:
      context: ./python/
      dockerfile: Dockerfile
    volumes:
      - ./python:/mnt
    ports:
      - 5100:5000
    command: /bin/bash -c "pip install -r requirements.txt && python app.py"
  # nodejs:
  #   image: node:latest
  #   container_name: nodejs
  #   working_dir: /app
  #   depends_on:
  #     - postgis
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./nodejs:/app
  #   command: /bin/bash -c "npm install && npm i -g nodemon && nodemon app.js"
